# -*- coding: utf-8 -*-
"""Generate random sample of images.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l4vncz8H48D7GwB8NAxyYjwFt3pC26IK

Extracting a random sample of 100 images and placing them in a new folder
"""

import os
import numpy as np
import shutil

source_dir = '/content/drive/MyDrive/NLP data dissertation/CS Photos'
dest_dir = '/content/drive/MyDrive/NLP data dissertation/CS Photos Sample'

images = os.listdir(source_dir)
n_sample_images = 100
subset_images = np.random.choice(images, size=n_sample_images, replace=False)

for image in subset_images:
    src_path = os.path.join(source_dir, image)
    dest_path = os.path.join(dest_dir, image)
    shutil.copy(src_path, dest_path)

source_dir2 = '/content/drive/MyDrive/NLP data dissertation/FR Photos'
dest_dir2 = '/content/drive/MyDrive/NLP data dissertation/FR Photos Sample'

images2 = os.listdir(source_dir2)
n_sample_images2 = 100
subset_images2 = np.random.choice(images2, size=n_sample_images2, replace=False)

for image2 in subset_images2:
    src_path2 = os.path.join(source_dir2, image2)
    dest_path2 = os.path.join(dest_dir2, image2)
    shutil.copy(src_path2, dest_path2)